### ISSUE TITLE
Is it possible for this mod to provide Planescape: Torment Enhanced support?

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Renegade0/InfinityUI#20]
Is it possible for this mod to provide Planescape: Torment Enhanced support?
After modifying nemeless one's three Multiclass, the original UI was unable to properly support the character's spellcasting and thievery skills. Maybe this mod can fix it?

**Comment by Renegade0** [comment]
The mod will not support PST:EE. The engine is too different.

Dne po 5. 2. 2024 20:21 uživatel MephistoSatanDevil <
***@***.***> napsal:

**Comment by MephistoSatanDevil** [comment]
😟
